# Список оповещений пользователя
GET http://localhost:3000/api/notify HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWZiMjdlYzk3YmM3MGMzYThlMWY0ZmYiLCJlbWFpbCI6InVzZXJAZm91bmQubG9jYWwiLCJyb2xlIjoi0YLRgNC10L3QtdGAIiwibmFtZSI6Iktla3MiLCJhdmF0YXIiOiJwaG90by0yLnBuZyIsImlzUmVhZHkiOnRydWUsImlhdCI6MTcxMjA4MjU3MCwiZXhwIjoxNzEyMDgzNDcwfQ.6psHSCjERN7ALjPtFMuHDoUz-Jq5go1JxUAfEq65s74

###

# Удалить оповещение
DELETE http://localhost:3000/api/notify/ec998270-3efc-48ee-b3a6-2684ddd278b1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWZiMjdlYzk3YmM3MGMzYThlMWY0ZmYiLCJlbWFpbCI6InVzZXJAZm91bmQubG9jYWwiLCJyb2xlIjoi0YLRgNC10L3QtdGAIiwibmFtZSI6Iktla3MiLCJhdmF0YXIiOiJwaG90by0yLnBuZyIsImlzUmVhZHkiOnRydWUsImlhdCI6MTcxMjA4MjU3MCwiZXhwIjoxNzEyMDgzNDcwfQ.6psHSCjERN7ALjPtFMuHDoUz-Jq5go1JxUAfEq65s74

###
