import { getRandomEnumValue } from "../../../helpers";
import { Gender, Level, TrainingTime, TrainingType } from "../../../types";

export const mockTrainings = [
  {
    title: 'Йога на открытом воздухе',
    background: '/public/images/training-yoga.jpg',
    level: getRandomEnumValue(Level),
    trainingType: TrainingType.Yoga,
    trainingTime: getRandomEnumValue(TrainingTime),
    price: 500,
    calories: 500,
    description: 'Прекрасная утреннняя йога для ума',
    gender: getRandomEnumValue(Gender),
    video: '/public/video/training-yoga.mp4',
    rating: 0,
    coachId: null,
    isFeatured: true,
  },
  {
    title: 'Бег вдоль пляжа Клеопатра',
    background: '/public/images/training-running.jpg',
    level: getRandomEnumValue(Level),
    trainingType: TrainingType.Running,
    trainingTime: getRandomEnumValue(TrainingTime),
    price: 500,
    calories: 500,
    description: 'Прекрасная утреннняя пробежка под палащим средиземноморским солнцем',
    gender: getRandomEnumValue(Gender),
    video: '/public/video/training-running.mp4',
    rating: 0,
    coachId: null,
    isFeatured: true,
  },
  {
    title: 'Бокс под открытым небом',
    background: '/public/images/training-boxing.jpg',
    level: getRandomEnumValue(Level),
    trainingType: TrainingType.Boxing,
    trainingTime: getRandomEnumValue(TrainingTime),
    price: 500,
    calories: 500,
    description: 'Бокс под открытым небом под шум волн',
    gender: getRandomEnumValue(Gender),
    video: '/public/video/training-boxing.mp4',
    rating: 0,
    coachId: null,
    isFeatured: true,
  },
  {
    title: 'Растяжка на пляже Алании',
    background: '/public/images/training-stretch.jpg',
    level: getRandomEnumValue(Level),
    trainingType: TrainingType.Stretching,
    trainingTime: getRandomEnumValue(TrainingTime),
    price: 500,
    calories: 500,
    description: 'Растяжка на горячем песке с последующим купанием',
    gender: getRandomEnumValue(Gender),
    video: '/public/video/training-stretch.mp4',
    rating: 0,
    coachId: null,
    isFeatured: true,
  },
  {
    title: 'Кроссфит для всего',
    background: '/public/images/training-crossfit.jpg',
    level: getRandomEnumValue(Level),
    trainingType: TrainingType.Crossfit,
    trainingTime: getRandomEnumValue(TrainingTime),
    price: 500,
    calories: 500,
    description: 'Тренировка силы и выносивости с видом на море',
    gender: getRandomEnumValue(Gender),
    video: '/public/video/training-crossfit.mp4',
    rating: 0,
    coachId: null,
    isFeatured: true,
  },
]
