import { getRandomEnumValue } from "../../../helpers";
import { Gender, Level, TrainingTime, TrainingType } from "../../../types";

export const mockTrainings = [
  {
    title: 'Йога на море',
    background: 'http://localhost:3000/mock-images/training-image/training-1.jpg',
    level: getRandomEnumValue(Level),
    trainingType: TrainingType.Yoga,
    trainingTime: getRandomEnumValue(TrainingTime),
    price: 500,
    calories: 500,
    description: 'Прекрасная утреннняя йога для ума',
    gender: getRandomEnumValue(Gender),
    video: '/video/training-yoga.mp4',
    rating: 0,
    coachId: null,
    isFeatured: false,
  },
  {
    title: 'Бег под водой',
    background: 'http://localhost:3000/mock-images/training-image/training-1.jpg',
    level: getRandomEnumValue(Level),
    trainingType: TrainingType.Running,
    trainingTime: getRandomEnumValue(TrainingTime),
    price: 700,
    calories: 400,
    description: 'Прекрасная утреннняя пробежка под палащим средиземноморским солнцем',
    gender: getRandomEnumValue(Gender),
    video: '/video/training-running.mp4',
    rating: 0,
    coachId: null,
    isFeatured: false,
  },
  {
    title: 'Бокс на улице',
    background: 'http://localhost:3000/mock-images/training-image/training-3.jpg',
    level: getRandomEnumValue(Level),
    trainingType: TrainingType.Boxing,
    trainingTime: getRandomEnumValue(TrainingTime),
    price: 1500,
    calories: 300,
    description: 'Бокс под открытым небом под шум волн',
    gender: getRandomEnumValue(Gender),
    video: '/video/training-boxing.mp4',
    rating: 0,
    coachId: null,
    isFeatured: false,
  },
  {
    title: 'Растяжка утром',
    background: 'http://localhost:3000/mock-images/training-image/training-2.jpg',
    level: getRandomEnumValue(Level),
    trainingType: TrainingType.Stretching,
    trainingTime: getRandomEnumValue(TrainingTime),
    price: 2500,
    calories: 100,
    description: 'Растяжка на горячем песке с последующим купанием',
    gender: getRandomEnumValue(Gender),
    video: '/video/training-stretch.mp4',
    rating: 0,
    coachId: null,
    isFeatured: false,
  },
  {
    title: 'Кроссфит #1',
    background: 'http://localhost:3000/mock-images/training-image/training-4.jpg',
    level: getRandomEnumValue(Level),
    trainingType: TrainingType.Crossfit,
    trainingTime: getRandomEnumValue(TrainingTime),
    price: 5500,
    calories: 200,
    description: 'Тренировка силы и выносивости с видом на море',
    gender: getRandomEnumValue(Gender),
    video: '/video/training-crossfit.mp4',
    rating: 0,
    coachId: null,
    isFeatured: false,
  },
]
