import { getRandomEnumValue } from "../../../helpers";
import { Level, Metro, TrainingTime } from "../../../types";

const DEFAULT_PASSWORD = '123456';

export const mockUsers = [
  {
    name: 'Василий',
    email: `vasya@local.mail`,
    password: DEFAULT_PASSWORD,
    gender: 'мужской',
    role: 'пользователь',
    description: 'Я - Василий, и я буду атлетом-качком через 2 месяца.',
    metro: getRandomEnumValue(Metro),
    background: '/public/images/vasya.jpg',
    level: getRandomEnumValue(Level),
    trainingType: ['бег', 'бокс'],
    trainingTime: getRandomEnumValue(TrainingTime),
    friends: [],
    isReady: true,
  },
  {
    name: 'Таня',
    email: `tanya@local.mail`,
    password: DEFAULT_PASSWORD,
    gender: 'женский',
    role: 'пользователь',
    description: 'Я - Таня, и я буду йогом-космонавтом через 1 месяц.',
    metro: getRandomEnumValue(Metro),
    background: '/public/images/tanyas.jpg',
    level: getRandomEnumValue(Level),
    trainingType: ['йога', 'стрейчинг'],
    trainingTime: getRandomEnumValue(TrainingTime),
    friends: [],
    isReady: true,
  },
  {
    name: 'Семен',
    email: `semen@local.mail`,
    password: DEFAULT_PASSWORD,
    gender: 'мужской',
    role: 'пользователь',
    description: 'Я - Семен, и я буду беби-йодой через 2 месяца.',
    metro: getRandomEnumValue(Metro),
    background: '/public/images/semen.jpg',
    level: getRandomEnumValue(Level),
    trainingType: ['бокс', 'стрейчинг'],
    trainingTime: getRandomEnumValue(TrainingTime),
    friends: [],
    isReady: true,
  },
  {
    name: 'Евгения',
    email: `user@fitfriends.local`,
    password: DEFAULT_PASSWORD,
    gender: 'женский',
    role: 'пользователь',
    description: 'Я - Женя, и я буду балериной через 3 месяца.',
    metro: getRandomEnumValue(Metro),
    background: '/public/images/evgeniya.jpg',
    level: getRandomEnumValue(Level),
    trainingType: ['бег', 'стрейчинг'],
    trainingTime: getRandomEnumValue(TrainingTime),
    friends: [],
    isReady: false,
  },
  {
    name: 'Бравый Тренер',
    email: `trainer@local.mail`,
    password: DEFAULT_PASSWORD,
    gender: 'мужской',
    role: 'тренер',
    description: 'Я - Тренер, я Супертренер!',
    metro: getRandomEnumValue(Metro),
    background: '/public/images/trainer.jpg',
    level: getRandomEnumValue(Level),
    trainingType: ['бокс', 'кроссфит', 'аэробика'],
    trainingTime: getRandomEnumValue(TrainingTime),
    friends: [],
    isReady: true,
  },
]
