version: '3.9'
services:
  fitfriends.postgres:
    image: postgres:16-alpine
    container_name: fitfriends.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - fitfriends.postgres:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d {POSTGRES_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - fitfriends

  fitfriends.pgadmin:
    image: dpage/pgadmin4:8.5
    container_name: fitfriends.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 8083:80
    depends_on:
      - fitfriends.postgres
    networks:
      - fitfriends

volumes:
  fitfriends.postgres:

networks:
  fitfriends:
      driver: bridge

# Запуск: docker-compose up -d
