version: '3.9'
services:
  fitfriends.postgres:
    image: postgres:16-alpine
    container_name: fitfriends.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - fitfriends.postgres:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d {POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - fitfriends

  fitfriends.pgadmin:
    image: dpage/pgadmin4:8.6
    container_name: fitfriends.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 8083:80
    depends_on:
      - fitfriends.postgres
    networks:
      - fitfriends

  fitfriends.subscribe.fakesmtp:
    image: gessnerfl/fake-smtp-server:2.2.1
    container_name: "fitfriends.subscribe.fakesmtp"
    hostname: "fitfriends.subscribe.fakesmtp"
    ports:
      - "${MAIL_SMTP_PORT}:8025"
      - 1083:8080

  fitfriends.subscribe.rabbitmq:
    image: rabbitmq:3.13.1-management
    container_name: fitfriends.subscribe.rabbitmq

    ports:
      - "${RABBIT_PORT}:5672"
      - 1088:15672

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  fitfriends.postgres:

networks:
  fitfriends:
      driver: bridge

# Запуск: docker-compose up -d
# Удалить все тома и начать заново: docker volume rm $(docker volume ls -q) -
