# Подписаться на уведомления о новых тренировках
POST http://localhost:3000/api/subscribe/02ef1619-0823-4c95-a66a-84c6cd0abbb4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWZiMjdjNjk3YmM3MGMzYThlMWY0ZmMiLCJlbWFpbCI6InVzZXJAbm90Zm91bi5sb2NhbCIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJuYW1lIjoiS2VrcyIsImF2YXRhciI6InBob3RvLTEucG5nIiwiaXNSZWFkeSI6dHJ1ZSwiaWF0IjoxNzEyMjgxNjA5LCJleHAiOjE3MTIyODI1MDl9.AF67zf6sE6Kycl-x5nutvQeNfrtbE8MKZh5K1ZB48Zo

###

# Отписаться от уведомлений о новых тренировках
DELETE http://localhost:3000/api/subscribe/02ef1619-0823-4c95-a66a-84c6cd0abbb4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWZiMjIyNGRkYmFjNzg5ZDMzMjE0NDciLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Iktla3MiLCJhdmF0YXIiOiJwaG90by0xLnBuZyIsImlzUmVhZHkiOnRydWUsImlhdCI6MTcxMjI4NDMyMywiZXhwIjoxNzEyMjg1MjIzfQ.lLrIg5V18qlO3zyYqLMLaImKJWTyOUNcytcdt5n0hlw

###
