# Получить отзывы о тренировке
GET http://localhost:3000/api/review/02ef1619-0823-4c95-a66a-84c6cd0abbb4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWZiMjIyNGRkYmFjNzg5ZDMzMjE0NDciLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Iktla3MiLCJhdmF0YXIiOiJwaG90by0xLnBuZyIsImlzUmVhZHkiOmZhbHNlLCJpYXQiOjE3MTE5ODkwNzEsImV4cCI6MTcxMTk4OTk3MX0.sV7Z97IiZE5dieeJP0XTIaIiljENxVvJaSyMPiQWnsQ

###

# Добавить новый отзыв о тренировке
POST http://localhost:3000/api/review HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWZiMjIyNGRkYmFjNzg5ZDMzMjE0NDciLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6Iktla3MiLCJhdmF0YXIiOiJwaG90by0xLnBuZyIsImlzUmVhZHkiOmZhbHNlLCJpYXQiOjE3MTE5ODkwNzEsImV4cCI6MTcxMTk4OTk3MX0.sV7Z97IiZE5dieeJP0XTIaIiljENxVvJaSyMPiQWnsQ

{
  "trainingId": "02ef1619-0823-4c95-a66a-84c6cd0abbb4",
  "grade": 5,
  "text": "Прекрасная тренировка на пляже средиземноморья, очень понравилось!"
}

###
